#!/bin/bash

OS=$(uname -s)

cd ~
if [ -f ".gitconfig" ]; then
    echo ".gitconfig already exists"
    exit 1
fi

## Git Config
git clone git@github.com:alexbarnsley/dotfiles.git
mv dotfiles/.git* .
rm -rf dotfiles

ALIASES_FILE=""
if [ -f ".bash_aliases" ]; then
    ALIASES_FILE=".bash_aliases"
elif [ -f ".bashrc" ]; then
    ALIASES_FILE=".bashrc"
elif [ -f ".profile" ]; then
    ALIASES_FILE=".profile"
else
    echo "No file for aliases"
    exit 1
fi

ALIAS_EXISTS=$(egrep "^alias g=\"git\"$" "$ALIASES_FILE")
if [ -z "$ALIAS_EXISTS" ]; then
    echo 'alias g="git"' >> "$ALIASES_FILE"
fi

## Node Installation
if [ "$OS" == "Linux" ]; then
	## Install NodeJS & NPM
	NODE_VERSION=$((node -v | egrep -o "[0-9]+" | head -1) 2>/dev/null || echo 0)
	if [ "$NODE_VERSION" -lt "11" ]; then
		curl -sL https://deb.nodesource.com/setup_11.x | sudo bash -
		sudo apt-get update && sudo apt-get install -y nodejs
	fi

	## Install Yarn
	YARN_VERSION=$(yarn -v 2>/dev/null)
	if [ -z "$YARN_VERSION" ]; then
		curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
		echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
		sudo apt-get update && sudo apt-get install -y yarn
	fi

	sudo su "$USER"

	## Add global yarn package
	yarn global add n
fi
